showPopupAlerts: yes
appTheme: cerulean
mapPanelWidth: 5
panoPanelWidth: 4
formPanelWidth: 3
mapPanelSource: Esri.WorldImagery
mapIconColour: green
mapMarkerColour: white
mapPolygonStroke: yes
mapPolygonStrokeColour: red
mapPolygonStrokeWeight: 2
mapPolygonStrokeOpacity: 0.5
mapPolygonFill: yes
mapPolygonFillColour: purple
mapPolygonFillOpacity: 0.2
pano360IconColour: blue
pano360MarkerColour: white
pano360PolygonStroke: yes
pano360PolygonStrokeColour: navy
pano360PolygonStrokeWeight: 2
pano360PolygonStrokeOpacity: 0.5
showPano360PolygonStrokeInCropExport: yes
pano360PolygonFill: yes
pano360PolygonFillColour: purple
pano360PolygonFillOpacity: 0.2
showPano360PolygonFillInCropExport: no
usernameLookupFile: username_lookup.csv
exportFileFormat: csv
lookup1Label: Species
lookup1CsvFile: Species_list_lookup.csv
lookup1HelpFile: Species_ID_Help.pdf
lookup2Label: Lookup_2
lookup2CsvFile: lookup2.csv
lookup2HelpFile: Species_ID_Help.pdf
lookup2Enabled: no
lookup3Label: Lookup_3
lookup3CsvFile: lookup3.csv
lookup3HelpFile: Species_ID_Help.pdf
lookup3Enabled: no
lookup4Label: Lookup_4
lookup4CsvFile: lookup4.csv
lookup4HelpFile: Species_ID_Help.pdf
lookup4Enabled: no
