appTheme: cerulean
mapPanelWidth: 5
panoPanelWidth: 5
formPanelWidth: 2
mapPanelSource: Esri.WorldImagery
usernameLookupFile: extdata/username_lookup.csv
exportFileFormat: csv
lookup1Label: Species
lookup1CsvFile: ./extdata/Species_list_lookup.csv
lookup1HelpFile: extdata/Species_ID_Help.pdf
lookup2Label: Lookup_2
lookup2CsvFile: extdata/Species_list_lookup.csv
lookup2HelpFile: extdata/Species_ID_Help.pdf
lookup2Enabled: no
lookup3Label: Lookup_3
lookup3CsvFile: extdata/Species_list_lookup.csv
lookup3HelpFile: extdata/Species_ID_Help.pdf
lookup3Enabled: no
lookup4Label: Lookup_4
lookup4CsvFile: extdata/Species_list_lookup.csv
lookup4HelpFile: extdata/Species_ID_Help.pdf
lookup4Enabled: no
