showPopupAlerts: yes
appTheme: cerulean
mapPanelWidth: 5
panoPanelWidth: 5
formPanelWidth: 2
mapPanelSource: Esri.WorldImagery
mapIconColour: green
mapMarkerColour: white
mapPolygonStroke: yes
mapPolygonStrokeColour: blue
mapPolygonStrokeWeight: 2
mapPolygonStrokeOpacity: 0.7
mapPolygonFill: yes
mapPolygonFillColour: navy
mapPolygonFillOpacity: 0.3
pano360IconColour: maroon
pano360MarkerColour: white
pano360PolygonStroke: yes
pano360PolygonStrokeColour: blue
pano360PolygonStrokeWeight: 1
pano360PolygonStrokeOpacity: 0.9
showPano360PolygonStrokeInCropExport: yes
pano360PolygonFill: yes
pano360PolygonFillColour: purple
pano360PolygonFillOpacity: 0.1
showPano360PolygonFillInCropExport: no
usernameLookupFile: username_lookup.csv
exportFileFormat: csv
lookup1Label: Species
lookup1CsvFile: Species_list_lookup.csv
lookup1HelpFile: Species_ID_Help.pdf
lookup2Label: Lookup_2
lookup2CsvFile: lookup2.csv
lookup2HelpFile: Species_ID_Help.pdf
lookup2Enabled: no
lookup3Label: Lookup_3
lookup3CsvFile: lookup3.csv
lookup3HelpFile: Species_ID_Help.pdf
lookup3Enabled: no
lookup4Label: Lookup_4
lookup4CsvFile: lookup4.csv
lookup4HelpFile: Species_ID_Help.pdf
lookup4Enabled: no
