---
title: "todos"
format: html
editor: visual
---

# TODO

- Fix run_app() after closing and then restarting again but only by run_app() Error in if: argument of length zero. ie. not restarting session.

- fix panellum displaying error on first load without image option - (DONE)

- fix purple image (current image) staying when new new kmz - (DONE)

- check latitude and longitude have - for S etc...(DONE)

- check themes on all shinyWidgets - switching to bslib?

- warning popup on change of lookups in the settings

- possibly add a wait icon progressbar on export cropped images - (DONE)

- fix icon on whole image icon not showing (DONE)

- fix polygon fill opacity on export images (DONE)

- add export cropped polygons from image - (DONE)

- add geocode metadata to exported images - (DONE)

- add help rmds - (DONE)

- add text in control form for current image filename - (DONE)

- add function for drawing overlay to PNG FOR PANNELLUM (STARTED)

- look at files export slow to load network drives

- Check screen greying over on leaving idol for ?? time

- look into polygon dissapearing after being drawn, annotation added but the polygon not drawn.

- need to look at all usernames being changed on edits from file happened when un-hooked username to rds.

- look at setting bounds for drawing on 360 images as currently one can draw polygons outside the pixels of the image

- fix stroke on polygons not show when stroke unchecked

- fix settings panel horizontal scroll bar from appearing

- make data load lowercase jpg and JPG when loading image metadata.

- move custom js to handlers.js file

- add stoke/fill options for overlay maps in settings panel

- add dashed line option for polygons

- add warning popup when changing lookup settings

- add click on images in the mapping panel to open them in the image panel

- add collection of annotation items so they can all be collapsed together

- add overlays to panellum

- add dashed line option to polygons

- check white space around exported images from crops

- add option to export png's and jpgs

- add functions/button to delete all annotations for image.

- add remove overlay button

- add zoom to overlay button

- zoom to extents of polygons drawn on map when r\$current_image changes

- write unit test functions

- add 'restore defaults' button in settings for

- make kmz browse progress bars hide/switch to progressbar on exports.

- have warnings popup to reload page when changing username lookup file in settings

- fix it so that the lookups default and work even if someone deletes the files from the system.

- switch to \|\> instead of %\>% pipes

- see if measuring in pixels is possible in images

# 
